### ISSUE TITLE
Question: Clarifying data fields and records

### ISSUE THREAD

**Issue by smit1678** [MasterFacilityList/mfl_api#594]
I've noticed across all facilities that there a few fields that are unclear. The docs and code give a bit of insight but I have a couple questions to ask about the `created`, `date_approved`, `date_established`, and `date_requested` fields. The `servicedesk@health.go.ke` email said there were data quality issues but I have a couple questions to understand the current version of the data. 

From an example facility, http://kmhfl.health.go.ke/#/facility/rating/b6461cf0-7b29-4048-8f98-0fc988f8c147/map/: 

``` json
created: "2009-10-31T00:00:00Z"
date_approved: "2016-02-12T08:28:43.562Z"
date_established: "2016-03-17"
date_requested: "2009-10-31T00:00:00Z"
```

`date_established` seems to be all the same date, `2016-03-17` across facilities while `created` and `date_requested` have more varying and realistic dates. 

Two main questions: 
- What is `date_requested` and `date_approved` and what does the current date in those variables represent? 
- Is the `created` date the date the facility is listed to be built, or is it the date the record was created in a previous version of a database? 

@bmarika @ngash @ngurenyaga tagging you all since you might have some insight here.

**Comment by bmarika** [comment]
Thanks @smit1678 for the queries:
- To address your first question, there is an approval process that takes place before a facility is visible in the [public website ](http://kmhfl.health.go.ke). This approval process is both for newly created facilities and edited facility details. `date_requested` is the date when a **new facility** was created in the system before it was approved for it to be seen in the public site. It is an alias for the date when it was added in the system and thus resulting in `date_requested` being the same as `created`.
- `date_approved` is the date that a **facility's edits** were approved to be seen in the public site.
- On the second question: `created` is the timestamp the facility was added in the previous database.
- On the `date_established` being equal to "2016-03-17", this was a bug and has since been fixed and changes deployed to the test site(http://kmhfltest.health.go.ke/). The correct values for this field will be populated during the data clean up process since the field was not there in the previous database

**Comment by smit1678** [comment]
@bmarika Thanks, this is very helpful. Will close this ticket out since this has clarified things. Really nice work to everyone who has worked on this.

**Comment by bmarika** [comment]
You are welcome @smit1678
